version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: ggmaddr
    #   MONGO_INITDB_ROOT_PASSWORD: passgg
      # - MONGO_INITDB_ROOT_USERNAME=ggmaddr
    env_file: 
      - ./env/mongo.env
  server:
    build: ./server
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '80:80'
    volumes: 
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file: 
      - ./env/server.env
    depends_on:
      - mongodb
  client:
    build: ./client
    ports: 
      - '3000:3000'
    volumes: 
      - ./client:/app
      - /app/node_modules
    #this service needs open input connection
    stdin_open: true
    # = -it
    tty: true
    depends_on: 
      - server

volumes: 
  data:
  logs:
